version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue_frontend
    ports:
      - "5173:5173"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge